config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  # LOGIN AND SIGNUP ROUTES
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  post '/users/:id' => 'users#show', as: :user
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/signup' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

  # FACEBOOK LOGIN
  match 'auth/:provider/callback', to: 'sessions#fb_create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  
  # ALL OTHER ROUTES
  namespace :api do
    namespace :v1 do
    get 'search' => 'trends#search'
      resources :trends do
        resources :videos
        resources :comments
      end
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :trend
  belongs_to :user

  validates :body, presence: true
  validates :user_id, presence: true
  validates :trend_id, presence: true

end

app/models/trend.rb
class Trend < ActiveRecord::Base
  has_many :videos
  has_many :comments

  # MAKES SURE ALL HASHTAGS THAT ARE STORED ARE UNIQUE
  validates :hashtags, uniqueness: {scope: :hashtags, case_sensitive: false}, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :comments
  has_secure_password
  validates :name, uniqueness: {scope: :name}, presence: true
  # VALIDATES EMAIL USING REGEX
  validates :email, uniqueness: {scope: :email, case_sensitive: false},length: {minimum: 6}, presence: true
  validates :password_digest, presence: true

# FACEBOOK LOGIN, OMNIAUTH PARAMS INJECTED INTO OUR DATABASE
  def self.from_omniauth(auth)
     where({:provider => auth ['provider'], :uid => auth ['uid']}).first_or_initialize.tap do |user|
          user.provider = auth['provider']
          user.uid = auth['uid']
          user.name = auth ['info']['name']
          user.oauth_token = auth['credentials']['token']
          user.oauth_expires_at = Time.at(auth['credentials']['expires_at'])
          user.save!
    end
  end

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :trend

  # VALIDATES URL UNIQUENESS, AVOID DUPLICATOIN
  validates :url, uniqueness: {scope: :url}, presence: true

end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController

  def index
     @comments = Comment.find_by_trend_id(params[:trend_id])
     render json: @comments
  end

  private
  def comment_params
    params.require(:comment).permit(:user_id, :trend_id, :body)
  end

end

app/controllers/api/v1/trends_controller.rb
class Api::V1::TrendsController < ApplicationController


  def index
    trends = Trend.all
    render json: trends
  end

  def show
    trend = Trend.find(params[:id])
    render json: trend
  end

  def search
    trend = Trend.where(hashtags: params[:hashtags])
    render json: trend
  end

end

app/controllers/api/v1/videos_controller.rb
class Api::V1::VideosController < ApplicationController


  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.find_by_trend_id(params[:trend_id])
    render json: @videos , root: false
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    render json: @video
  end

  # POST /videos
  # POST /videos.json
  def create
    trend = Trend.find(params[:trend_id])
    if trend.videos.create(video_params)
      render json: @video, status: :created, location: @video
    else
      render json: @video.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    @video = video.find(params[:id])
    if @video.update(video_params)
      head :no_content
    else
      render json: @video.errors, status: :unprocessable_entity
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    head :no_content
  end

  private
  def set_video
    @video = video.find(params[:id])
  end

  def video_params
    params.require(:video).permit(:url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery with: :exception
  helper_method :current_user
  # before_filter :load_tweets

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
      return @current_user
    else
      return nil
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @trends = Trend.all
  end

  def create
    puts params
    @trends = Trend.find(params[:trend_id])
    @comment = @trend.comments.new(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    redirect_to root_path
  end

  def show
  end

  private
  def comment_params
    params.require(:comment).permit(:user_id, :trend_id, :body)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user=User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id]=user.id
      redirect_to('/')
    else
      flash[:error] = "Incorrect email or password"
      render '/'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to ('/')
  end

  def fb_create
     user = User.from_omniauth(request.env['omniauth.auth'])
     session[:user_id] = user.id
     redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to('/signup')
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
    def user_params
      params.permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

# GET /videos
  # GET /videos.json
  def index
    @videos = Video.all

    render json: @videos , root: false
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    render json: @video
  end
  # POST /videos
  # POST /videos.json
  def create
    @video = video.new(video_params)

    if @video.save
      render json: @video, status: :created, location: @video
    else
      render json: @video.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    @video = video.find(params[:id])

    if @video.update(video_params)
      head :no_content
    else
      render json: @video.errors, status: :unprocessable_entity
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy

    head :no_content
  end

  private

    def set_video
      @video = video.find(params[:id])
    end

    def video_params
      params.require(:video).permit(:url)
    end
end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  # ACTION THAT ALLOWS ME TO RENDER MY TRENDS
  def index
    @trends = Trend.last(15)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def load_tweets
    $twitter.home_timeline
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trends_helper.rb
module TrendsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<div class="container">
  <div class="comment-content">

    <h4>Comment:</h4>

    <p><%= comment.body %></p>

    <p><%= @user.name%></p>

    <% if current_user %>

      <p><%= link_to 'Destroy Comment', [comment.trend, comment],
          method: :delete,
          data: { confirm: 'Are you sure?' } %>
      </p>
    <% end %>

  </div>
</div>

app/views/comments/_new.html.erb
<div id="Comment" class="modal modal-fixed-footer">
  <div class="modal-content">
    <h4 id="modalHeaders">Add Comment</h4>
    <div class="row">
      <div class = "container">

        <%= form_for([@trend, @trend.comments.build])do %>

        <div class="row">
          <div class="input-field col s12">
            <%= text_field_tag :body,nil,class: "validate" %>
            <label for="write comment">speak your mind</label>
          </div>
        </div>

      </div>
    </div>
  </div>

  <div class="modal-footer">
    <button class="btn waves-effect waves-light" type="submit" name="action">Submit
      <i class="mdi-content-send right"></i>
    </button>
  </div>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>DoubleDigest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>

</head>

<body>

  <!-- SIGNUP MODAL -->
  <%= render 'users/new' %>

  <!-- SIGNIN MODAL -->
  <%= render 'sessions/new' %>

<main>

<%= yield %>

</main>

  <!-- FOOTER PARTIAL -->
  <%= render 'welcome/footer' %>


</body>
</html>

app/views/users/_new.html.erb
<!-- SIGNUP MODAL -->

<div id="Signup" class="modal modal-fixed-footer">
  <div class="modal-content">
    <h4 id="modalHeaders">Signup for Sway News</h4>
    <div class="row">
      <div class = "container">

        <%= form_tag('/signup', method: :post, :class => 'col s12') do %>

        <div class="row">
          <div class="input-field col s12">
            <%= text_field_tag :name,nil,class: "validate" %>
            <label for="first name">Username</label>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
            <%= text_field_tag :email,nil, class: "validate" %>
            <label for="email">Email</label>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
            <%= password_field_tag :password,nil, class: "validate" %>
            <label for="password">Password</label>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
            <%= password_field_tag :password,nil, class: "validate" %>
            <label for="password_confirmation">Confirm Password</label>
          </div>
        </div>

      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button class="btn waves-effect waves-light" type="submit" name="action">Submit
      <i class="mdi-content-send right"></i>
    </button>
  </div>
  <% end %>
</div>
          

app/views/welcome/_footer.html.erb
<!-- FOOTER -->
  <footer class="page-footer blue">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text" id="swaylogofoot">SWAY NEWS</h5>
          <p class="grey-text text-lighten-4">Swaying minds since 2015</p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text" id="swaylogofoot">Links</h5>
          <ul>
            <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Contact</a></li>

          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      © 2015 Project Unicorn Productions
        <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
      </div>
    </div>
  </footer>

app/views/welcome/index.html.erb
<!-- NAVBAR -->
<nav>
  <div class="nav-wrapper blue">

    <!-- TRENDS SIDEBAR -->
    <ul id="slide-out" class="side-nav  blue">
      <li class="topictext">TOPICS</li>
      <% @trends.each do |tweet| %>
      <li class="trendsclick"><%= tweet.hashtags %></li>
      <% end %>
    </ul>
    <a href="#" data-activates="slide-out" class="button-collapse show-on-large">
      <i class="mdi-navigation-menu"></i>
    </a>


    <!-- LOGO -->
    <div id="fade-in">
      <div class="brand-logo center" id="swaylogo">Sway News</div>
    </div>

    <!-- SIGNUP + SIGNIN -->
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if current_user %>
      <li>Welcome <strong><%= current_user.name%></strong></li>
      <li><%= link_to 'Signout', signout_path %></li>
      <% else %>

      <!-- SIGNUP MODAL BUTTON -->
      <a class="waves-effect waves-light btn modal-trigger red accent-4" href="#Signup" id="navbuttons">Sign Up</a>

      <!-- SIGNIN MODAL BUTTON-->
      <a class="waves-effect waves-light btn modal-trigger  red accent-4" href="#Signin" id="navbuttons2">Sign In</a>

      <% end %>
    </ul>

  </div>
</nav>

<!-- PAGE LAYOUT -->
<div id="fade-content">
  <div class="row" id="pageLayout">
    <div class="col s6 m6 l6 ">
      <div class = "newslogo"id="newsLogoCNN"></div>
        <div class="videoframe">
      
          <div class="embed-container-l" id="results"></div>
        </div>
    </div>
    <div class="col s6 m6 l6">
      <div class = "newslogo" id="newsLogoFox"></div>
        <div class="videoframe">
      
          <div class="embed-container-l" id="foxresults"></div>
        </div>
    </div>
  </div>
</div>
</div>
</div>